import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { Baseline, BaselineStep, Locator } from '../baseline/types.js';
import { ROOT } from '../config.js';

/**
 * Turning a recorded baseline into a Playwright spec file on disk.
 *
 * The requirement asks for executable test files, and until now there were none:
 * plan and baseline lived in SQLite and an interpreter replayed them. That is a
 * defensible architecture — it is what makes healing possible, because a locator
 * the system owns can be rewritten and a locator in someone's source file cannot —
 * but it leaves the team with nothing they can keep.
 *
 * The claim worth making about these files: **the locators in them were proven
 * against the running application.** Every one was resolved during recording,
 * checked for uniqueness, and confirmed to select the element the model chose
 * (`browser/locator.ts`). Most generated suites ship selectors the model guessed
 * and nobody executed. Every assertion here is likewise derived from what
 * Playwright observed after the step ran, not from what the plan hoped for.
 *
 * Re-emitted after a heal, which is the product thesis expressed as an artifact:
 * the file on disk tracks the application instead of rotting against it.
 */

export interface EmitResult {
  filePath: string;
  relativePath: string;
  steps: number;
  /** Steps whose locator was rewritten by the healer since first recording. */
  healed: number;
}

const OUT_DIR = path.join(ROOT, 'tests', 'generated');

export interface EmitOptions {
  /**
   * Values this pipeline authored for the plan, by reference name.
   *
   * Inlined as fallbacks so the file runs on a machine that never saw the mission.
   * They are test data, not secrets — a search term, a quantity, a deliberately
   * wrong password — and a spec that throws on a missing search term is a spec
   * nobody can execute outside the tool that produced it. Anything not listed here
   * is treated as a credential and still fails loudly rather than being written
   * into a file bound for a repository.
   */
  authoredValues?: Record<string, string>;
}

export async function emitSpec(
  baseline: Baseline,
  options: EmitOptions = {},
): Promise<EmitResult> {
  const slug = baseline.planId.replace(/[^A-Za-z0-9._-]/g, '-');
  const filePath = path.join(OUT_DIR, `${slug}.spec.ts`);
  const healed = baseline.steps.filter((step) => (step.healHistory?.length ?? 0) > 0).length;

  await mkdir(OUT_DIR, { recursive: true });
  await writeFile(filePath, renderSpec(baseline, healed, options.authoredValues ?? {}), 'utf8');

  return {
    filePath,
    relativePath: path.relative(ROOT, filePath),
    steps: baseline.steps.length,
    healed,
  };
}

function renderSpec(
  baseline: Baseline,
  healed: number,
  authored: Record<string, string>,
): string {
  const lines: string[] = [];

  lines.push(
    '/**',
    ` * ${titleOf(baseline.planId)}`,
    ' *',
    ' * Generated by EdgeForge. Every locator below was resolved against the running',
    ' * application and confirmed to select exactly one element, and every assertion was',
    " * derived from what the browser actually did after the step ran — not from a model's",
    ' * expectation. Regenerated whenever the healer repairs a step, so this file tracks',
    ' * the application rather than drifting from it.',
    ' *',
    ` * Plan       ${baseline.planId}`,
    ` * Recorded   ${baseline.createdAt}`,
    ` * Model      ${baseline.model}`,
    ` * Steps      ${baseline.steps.length}${healed ? ` (${healed} repaired since first recording)` : ''}`,
    ' *',
    ...(Object.keys(authored).length
      ? [
          ' *',
          ' * Test values this pipeline authored are inlined as fallbacks so this file runs',
          ' * anywhere: ' + Object.keys(authored).join(', ') + '.',
          ' * Credentials are not inlined and must come from the environment.',
        ]
      : []),
    ' *',
    ' * Edits here are lost on the next regeneration. Change the plan instead.',
    ' */',
    "import { expect, test } from '@playwright/test';",
    '',
    `test(${quote(titleOf(baseline.planId))}, async ({ page }) => {`,
    `  await page.goto(${quote(baseline.startUrl)});`,
    '',
  );

  for (const step of baseline.steps) {
    lines.push(`  // ${step.stepId}: ${step.intent}`);
    if (step.healHistory?.length) {
      // Disclosed rather than silently rewritten: a reader deserves to know this
      // locator is not the one first recorded, and why it changed.
      const last = step.healHistory[step.healHistory.length - 1]!;
      lines.push(
        `  // Repaired by the healer: ${last.reason ?? 'the original locator stopped matching'}`,
      );
    }
    lines.push(...renderStep(step, authored).map((line) => `  ${line}`), '');
  }

  lines.push('});', '');
  return lines.join('\n');
}

function renderStep(step: BaselineStep, authored: Record<string, string>): string[] {
  const lines: string[] = [];
  const target = step.locator ? locatorExpression(step.locator) : null;
  const value = valueExpression(step, authored);

  switch (step.action) {
    case 'navigate':
      lines.push(`await page.goto(${quote(step.value ?? step.pageUrl)});`);
      break;
    case 'fill':
      if (target) lines.push(`await ${target}.fill(${value});`);
      break;
    case 'click':
      if (target) lines.push(`await ${target}.click();`);
      break;
    case 'select':
      if (target) lines.push(`await ${target}.selectOption(${value});`);
      break;
    case 'check':
      if (target) lines.push(`await ${target}.check();`);
      break;
    case 'uncheck':
      if (target) lines.push(`await ${target}.uncheck();`);
      break;
    case 'press':
      if (target) lines.push(`await ${target}.press(${quote(step.value ?? 'Enter')});`);
      break;
    case 'hover':
      if (target) lines.push(`await ${target}.hover();`);
      break;
    case 'waitFor':
      if (target) lines.push(`await ${target}.waitFor();`);
      break;
    case 'assert':
      // Assertion-only steps carry their expectation below; nothing to act on.
      break;
    default:
      lines.push(`// Unsupported action "${String(step.action)}" — no code emitted.`);
  }

  lines.push(...renderAssertions(step));
  return lines.length ? lines : ['// Nothing executable was recorded for this step.'];
}

/**
 * The observed post-conditions, as real expectations.
 *
 * `none` emits a comment rather than a vacuous assertion. A generated test that
 * asserts something trivially true is worse than one that asserts nothing: it
 * reports confidence it does not have.
 */
function renderAssertions(step: BaselineStep): string[] {
  const outcome = step.expectedOutcome;
  if (!outcome) return [];

  // `expectedOutcome` is a record with an `assertions` array plus the plan's prose
  // expectation. Treating the record itself as an assertion emitted nothing at all.
  const assertions = outcome.assertions ?? [];
  const lines: string[] = [];

  if (assertions.length === 0) {
    return ['// Nothing verifiable changed after this step, so nothing is asserted.'];
  }

  for (const assertion of assertions) {
    const entry = assertion as { type?: string; value?: string | null; locator?: unknown };
    /**
     * The assertion's own locator when it has one. An assertion often checks a
     * different element than the step acted on — a click on "Sign in" asserts on the
     * error message — and reusing the step's target would check the button instead.
     */
    const assertionLocator = (entry.locator ?? step.locator) as Locator | null;
    const target = assertionLocator ? locatorExpression(assertionLocator) : null;

    switch (entry.type) {
      case 'urlContains':
        lines.push(`await expect(page).toHaveURL(new RegExp(${quote(escapeRegex(entry.value ?? ''))}));`);
        break;
      case 'elementVisible':
        if (target) lines.push(`await expect(${target}).toBeVisible();`);
        break;
      case 'textEquals':
        if (target) lines.push(`await expect(${target}).toHaveText(${quote(entry.value ?? '')});`);
        break;
      case 'inputFilled':
        if (target) lines.push(`await expect(${target}).not.toBeEmpty();`);
        break;
      default:
        break;
    }
  }
  return lines;
}

/**
 * The proven locator as a Playwright expression.
 *
 * Fallbacks are not emitted. The baseline holds ranked alternates because the
 * replayer tries them before it considers healing, and a spec file that raced
 * through four candidates would pass on a page where the intended element is gone —
 * turning a real failure into a silent one. The primary is the one that was proven.
 */
function locatorExpression(locator: Locator): string {
  const nth = locator.nth === null ? '' : `.nth(${locator.nth})`;

  switch (locator.strategy) {
    case 'testId':
      return `page.getByTestId(${quote(locator.value ?? '')})${nth}`;
    case 'role':
      return `page.getByRole(${quote(locator.role ?? 'button')}, { name: ${quote(locator.name ?? '')} })${nth}`;
    case 'label':
      return `page.getByLabel(${quote(locator.value ?? '')})${nth}`;
    case 'placeholder':
      return `page.getByPlaceholder(${quote(locator.value ?? '')})${nth}`;
    case 'altText':
      return `page.getByAltText(${quote(locator.value ?? '')})${nth}`;
    case 'text':
      return `page.getByText(${quote(locator.value ?? '')})${nth}`;
    case 'labelledBy':
      // The element that follows a label, which is how a displayed *value* gets an
      // identity that does not depend on its own content.
      return `page.locator(\`xpath=//*[normalize-space(text())=${quote(locator.value ?? '')}]/following::*[1]\`)${nth}`;
    case 'css':
      return `page.locator(${quote(locator.value ?? '')})${nth}`;
    default:
      return `page.locator(${quote(locator.value ?? '')})${nth}`;
  }
}

/**
 * A referenced value reads from the environment in the emitted file too.
 *
 * Inlining it would write a credential into a file destined for a repository. The
 * spec fails loudly on a missing variable instead, which is the same contract the
 * replayer honours.
 */
function valueExpression(step: BaselineStep, authored: Record<string, string>): string {
  if (step.valueRef) {
    const fallback = authored[step.valueRef];
    // Authored test data carries its value, so the file runs anywhere. A credential
    // does not: the spec fails loudly rather than embedding a secret in source.
    return fallback === undefined
      ? `process.env[${quote(step.valueRef)}] ?? (() => { throw new Error(${quote(
          `${step.valueRef} is not set`,
        )}); })()`
      : `process.env[${quote(step.valueRef)}] ?? ${quote(fallback)}`;
  }
  return quote(step.value ?? '');
}

function titleOf(planId: string): string {
  return planId
    .split(/[-_]/)
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
